fn:
  in-topic: fn-topic
  in-group: fn-group
  out-topic: ${fn.in-topic}}

liiklus:
  host: localhost
  port: 6565

spring:
  cloud:
    function:
      location: ${fn.location}
      function-class: ${fn.name}